// GENERATED by scripts/generate-customer-api-contract.mjs from
// contracts/customer-api.json. Do not edit by hand; run the generator and commit both outputs.

export const CUSTOMER_API_SCHEMA_VERSION = 1;
export const CUSTOMER_API_PREFIX = "/api/v1";

const routeList = [
  {
    "id": "source_search_sync",
    "path": "/search",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "search_source",
      "feature": "search",
      "credits": 5
    },
    "npmOperation": "searchSource",
    "mcpTool": "search_source",
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "q",
        "in": "query",
        "required": true,
        "example": "js.stripe.com/v3",
        "description": "Source substring or bounded literal expression"
      },
      {
        "name": "query_kind",
        "in": "query",
        "required": false,
        "example": "literal",
        "description": "literal or regex — regex needs Solo+"
      },
      {
        "name": "content_type",
        "in": "query",
        "required": false,
        "example": "js",
        "description": "html, js, css, json, text, or xml"
      },
      {
        "name": "site",
        "in": "query",
        "required": false,
        "example": "example.com",
        "description": "Restrict to one registrable domain"
      },
      {
        "name": "tld",
        "in": "query",
        "required": false,
        "example": "gov",
        "description": "TLD suffix filter"
      },
      {
        "name": "tech",
        "in": "query",
        "required": false,
        "example": "React",
        "description": "Comma list; sites using ALL of these technologies"
      },
      {
        "name": "category",
        "in": "query",
        "required": false,
        "example": "analytics",
        "description": "Comma list; sites using ANY of these categories"
      },
      {
        "name": "country",
        "in": "query",
        "required": false,
        "example": "CH,DE,PL",
        "description": "ISO country codes from hosting/ccTLD data; matches any listed country (CH = Switzerland, DE = Germany, PL = Poland)."
      },
      {
        "name": "max_results",
        "in": "query",
        "required": false,
        "example": "200000",
        "description": "Raise the job's result cap past your plan's depth (Solo+; rows past the depth are priced per page when served)"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Page size, clamped by tier result depth"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "example": "0",
        "description": "Rank-ordered offset"
      }
    ]
  },
  {
    "id": "source_search_create",
    "path": "/searches",
    "scope": "versioned",
    "method": "POST",
    "auth": "api_key",
    "meter": {
      "action": "search_source",
      "feature": "search",
      "credits": 5
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "q",
        "in": "body",
        "required": true,
        "example": "googletagmanager.com/gtag/js",
        "description": "Source substring or literal expression"
      },
      {
        "name": "query_kind",
        "in": "body",
        "required": false,
        "example": "literal",
        "description": "literal or regex — regex needs Solo+"
      },
      {
        "name": "country",
        "in": "body",
        "required": false,
        "example": "CH,DE,PL",
        "description": "ISO country codes from hosting/ccTLD data; matches any listed country (CH = Switzerland, DE = Germany, PL = Poland). Send a JSON array in API requests."
      },
      {
        "name": "max_results",
        "in": "body",
        "required": false,
        "example": "200000",
        "description": "Raise the job's result cap past your plan's depth (Solo+; rows past the depth are priced per page when served)"
      },
      {
        "name": "page_size",
        "in": "body",
        "required": false,
        "example": "50",
        "description": "1-500, clamped by tier result depth"
      }
    ]
  },
  {
    "id": "source_search_status",
    "path": "/searches/{id}",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "search_poll",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "example": "job-3f9c2e81",
        "description": "Search job id from the create response"
      }
    ]
  },
  {
    "id": "source_search_cancel",
    "path": "/searches/{id}",
    "scope": "versioned",
    "method": "DELETE",
    "auth": "api_key",
    "meter": {
      "action": "search_poll",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "example": "job-3f9c2e81",
        "description": "Search job id to cancel"
      }
    ]
  },
  {
    "id": "source_search_events",
    "path": "/searches/{id}/events",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "search_poll",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "example": "job-3f9c2e81",
        "description": "Search job id"
      }
    ]
  },
  {
    "id": "source_search_results",
    "path": "/searches/{id}/results",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "search_poll",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "example": "job-3f9c2e81",
        "description": "Search job id"
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "example": "",
        "description": "Opaque pagination cursor from the previous page"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Rows per page"
      }
    ]
  },
  {
    "id": "facet_count",
    "path": "/facet",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "facet_count",
      "feature": "tech",
      "credits": 1
    },
    "npmOperation": "facetCount",
    "mcpTool": "facet_count",
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "kind",
        "in": "query",
        "required": true,
        "example": "tech",
        "description": "tech, identifier, or request_host"
      },
      {
        "name": "signal",
        "in": "query",
        "required": true,
        "example": "google-analytics",
        "description": "Facet value to count: a technology name in any case or its slug, a request host, or an identifier value"
      },
      {
        "name": "id_type",
        "in": "query",
        "required": false,
        "example": "ga",
        "description": "Identifier family, required for identifier facets"
      }
    ]
  },
  {
    "id": "tech_query",
    "path": "/tech",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "tech_query",
      "feature": "tech",
      "credits": 3
    },
    "npmOperation": "techQuery",
    "mcpTool": "tech_query",
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "name",
        "in": "query",
        "required": false,
        "example": "Google Tag Manager",
        "description": "Exact technology name"
      },
      {
        "name": "name_slug",
        "in": "query",
        "required": false,
        "example": "google-tag-manager",
        "description": "Canonical route slug"
      },
      {
        "name": "category",
        "in": "query",
        "required": false,
        "example": "ecommerce",
        "description": "Detector category slug (mutually exclusive with name)"
      },
      {
        "name": "tech",
        "in": "query",
        "required": false,
        "example": "Klaviyo,Shopify",
        "description": "Comma list of up to 5 further technologies (names or slugs); a site must use ALL of them in addition to the selection"
      },
      {
        "name": "country",
        "in": "query",
        "required": false,
        "example": "CH,DE,PL",
        "description": "Comma-separated ISO country codes from hosting/ccTLD data; matches any listed country (CH = Switzerland, DE = Germany, PL = Poland)."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Maximum rows"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "example": "0",
        "description": "Rank-ordered offset for paging; rows past your plan's result depth cost overage credits on Solo+ (1 per started 100 rows), Free stops at its depth"
      }
    ]
  },
  {
    "id": "domain_export",
    "path": "/tech/export",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "domain_export",
      "feature": "export",
      "credits": 5
    },
    "npmOperation": "exportTechnology",
    "mcpTool": null,
    "webOperation": null,
    "minTier": "solo",
    "params": [
      {
        "name": "name",
        "in": "query",
        "required": false,
        "example": "Shopify",
        "description": "Exact technology name (or use name_slug / category)"
      },
      {
        "name": "name_slug",
        "in": "query",
        "required": false,
        "example": "shopify",
        "description": "Canonical technology slug"
      },
      {
        "name": "category",
        "in": "query",
        "required": false,
        "example": "ecommerce",
        "description": "Detector category slug instead of one technology"
      },
      {
        "name": "tech",
        "in": "query",
        "required": false,
        "example": "Klaviyo",
        "description": "Comma list of up to 5 further technologies a site must ALSO use"
      },
      {
        "name": "country",
        "in": "query",
        "required": false,
        "example": "DE,AT,CH",
        "description": "ISO country codes; matches any listed country"
      },
      {
        "name": "format",
        "in": "query",
        "required": false,
        "example": "csv",
        "description": "csv (default) or jsonl; rows capped at the plan's export row limit, rows past the result depth cost overage credits"
      }
    ]
  },
  {
    "id": "site_profile",
    "path": "/site",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "tech_lookup",
      "feature": "profile",
      "credits": 3
    },
    "npmOperation": "techLookup",
    "mcpTool": "tech_lookup",
    "webOperation": null,
    "minTier": "pro",
    "params": [
      {
        "name": "domain",
        "in": "query",
        "required": true,
        "example": "example.com",
        "description": "Registrable domain to profile"
      }
    ]
  },
  {
    "id": "source_read",
    "path": "/source/{blob_hash}",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "source_read",
      "feature": "profile",
      "credits": 5
    },
    "npmOperation": "readSource",
    "mcpTool": "read_source",
    "webOperation": null,
    "minTier": "pro",
    "params": [
      {
        "name": "blob_hash",
        "in": "path",
        "required": true,
        "example": "3f9c2e81ab6d4c07e9a1b2c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5061",
        "description": "The 64-character blob hash of a search hit"
      },
      {
        "name": "content_type",
        "in": "query",
        "required": true,
        "example": "html",
        "description": "The hit's content type: html, js, css, json, text, or xml"
      }
    ]
  },
  {
    "id": "owner_graph",
    "path": "/owner-graph",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "owner_graph",
      "feature": "owner_graph",
      "credits": 5
    },
    "npmOperation": "ownerGraph",
    "mcpTool": "owner_graph",
    "webOperation": null,
    "minTier": "pro",
    "params": [
      {
        "name": "id",
        "in": "query",
        "required": true,
        "example": "UA-7870337-1",
        "description": "Tracker/ad account id to resolve"
      },
      {
        "name": "id_type",
        "in": "query",
        "required": true,
        "example": "ga",
        "description": "Identifier family: ga, ga4, gtm, adsense, fb_pixel, google_ads, hotjar, mixpanel, segment, clarity, yandex_metrica"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Maximum domains"
      }
    ]
  },
  {
    "id": "domain_browse",
    "path": "/domains",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "domain_browse",
      "feature": "tech",
      "credits": 1
    },
    "npmOperation": "browseDomains",
    "mcpTool": "browse_domains",
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "q",
        "in": "query",
        "required": false,
        "example": "stripe",
        "description": "Substring of the registrable domain (3+ chars)"
      },
      {
        "name": "tld",
        "in": "query",
        "required": false,
        "example": "com",
        "description": "TLD suffix filter"
      },
      {
        "name": "tech",
        "in": "query",
        "required": false,
        "example": "React",
        "description": "Restrict to sites using this technology"
      },
      {
        "name": "country",
        "in": "query",
        "required": false,
        "example": "CH,DE,PL",
        "description": "Comma-separated ISO country codes from hosting/ccTLD data; matches any listed country (CH = Switzerland, DE = Germany, PL = Poland)."
      },
      {
        "name": "sort",
        "in": "query",
        "required": false,
        "example": "rank",
        "description": "Only rank is supported"
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Page size"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "example": "0",
        "description": "Row offset into the ordered result. Honoured at any depth (never clamped), but the cost of an offset page grows with its depth; walk deep result sets with cursor instead."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "example": "",
        "description": "Opaque next_cursor / previous_cursor from a previous page. A cursor page costs the same at any depth and takes precedence over offset. Read has_more and next_cursor to detect the end, never the page size."
      }
    ]
  },
  {
    "id": "shop_browse",
    "path": "/shops",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "shop_browse",
      "feature": "shop_catalog",
      "credits": 1
    },
    "npmOperation": "listShops",
    "mcpTool": "list_shops",
    "webOperation": null,
    "minTier": "enterprise",
    "params": [
      {
        "name": "q",
        "in": "query",
        "required": false,
        "example": "example",
        "description": "Case-insensitive domain substring, 3–253 characters: letters, digits, hyphens, dots, or underscores; no consecutive dots, URLs, spaces, or wildcards. Omit to browse all shops. Search product titles with /shop/products instead."
      },
      {
        "name": "country",
        "in": "query",
        "required": false,
        "example": "CH,DE,PL",
        "description": "ISO country codes from hosting/ccTLD data; matches any listed country (CH = Switzerland, DE = Germany, PL = Poland)."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Page size"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "example": "0",
        "description": "Row offset into the ordered result. Honoured at any depth (never clamped), but the cost of an offset page grows with its depth; walk deep result sets with cursor instead."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "example": "",
        "description": "Opaque next_cursor / previous_cursor from a previous page. A cursor page costs the same at any depth and takes precedence over offset. Read has_more and next_cursor to detect the end, never the page size."
      }
    ]
  },
  {
    "id": "shop_stats",
    "path": "/shops/stats",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "shop_stats",
      "feature": "shop_catalog",
      "credits": 1
    },
    "npmOperation": "shopStats",
    "mcpTool": "shop_stats",
    "webOperation": null,
    "minTier": "enterprise",
    "params": []
  },
  {
    "id": "shop_products",
    "path": "/shop/products",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "shop_products",
      "feature": "shop_catalog",
      "credits": 2
    },
    "npmOperation": "shopProducts",
    "mcpTool": "shop_products",
    "webOperation": null,
    "minTier": "enterprise",
    "params": [
      {
        "name": "domain",
        "in": "query",
        "required": false,
        "example": "example.com",
        "description": "One shop's registrable domain; omit to browse all"
      },
      {
        "name": "q",
        "in": "query",
        "required": false,
        "example": "widget",
        "description": "Case-insensitive substring on the product title"
      },
      {
        "name": "vendor",
        "in": "query",
        "required": false,
        "example": "Samsung",
        "description": "Exact vendor (brand) string as the storefront publishes it"
      },
      {
        "name": "country",
        "in": "query",
        "required": false,
        "example": "CH,DE,PL",
        "description": "ISO country codes from hosting/ccTLD data; matches any listed country (CH = Switzerland, DE = Germany, PL = Poland)."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Page size"
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "example": "0",
        "description": "Row offset into the ordered result. Honoured at any depth (never clamped), but the cost of an offset page grows with its depth; walk deep result sets with cursor instead."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "example": "",
        "description": "Opaque next_cursor / previous_cursor from a previous page. A cursor page costs the same at any depth and takes precedence over offset. Read has_more and next_cursor to detect the end, never the page size."
      }
    ]
  },
  {
    "id": "shop_discovery",
    "path": "/shops/discovery",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "shop_browse",
      "feature": "shop_catalog",
      "credits": 1
    },
    "npmOperation": "discoverShops",
    "mcpTool": null,
    "webOperation": null,
    "minTier": "enterprise",
    "params": [
      {
        "name": "platform",
        "in": "query",
        "required": true,
        "example": "wix",
        "description": "Catalog platform ID: shopify, woocommerce, magento, wix, prestashop, shopware, bigcommerce, squarespace, opencart, bitrix, shoptet, ecwid, lightspeed, eccube, or bigcartel. Returns verified storefronts, including confirmed empty shops, with explicit coverage and freshness."
      },
      {
        "name": "domain",
        "in": "query",
        "required": false,
        "example": "example.com",
        "description": "Exact lower-case registrable domain; multiple tenant storefronts remain separate."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "example": "",
        "description": "Opaque next_cursor from the previous page; reuse the same filters. Pages reflect current observations, not a frozen catalog view."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "50",
        "description": "Candidate window size, 1–200 (default 50). Only verified shops are returned; a page may be empty and still have next_cursor. Continue until next_cursor is null. No global total or offset."
      }
    ]
  },
  {
    "id": "shop_catalog_v2",
    "path": "/shop/catalog",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "shop_products",
      "feature": "shop_catalog",
      "credits": 2
    },
    "npmOperation": "shopCatalog",
    "mcpTool": null,
    "webOperation": null,
    "minTier": "enterprise",
    "params": [
      {
        "name": "platform",
        "in": "query",
        "required": true,
        "example": "wix",
        "description": "Exact platform from /shops/discovery."
      },
      {
        "name": "domain",
        "in": "query",
        "required": true,
        "example": "example.com",
        "description": "Exact reg_domain from /shops/discovery."
      },
      {
        "name": "shop_key",
        "in": "query",
        "required": true,
        "example": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "description": "Full 64-character storefront/scope key from /shops/discovery; a domain alone is not a shop identity. Returns raw string IDs, embedded offers and nullable source timestamps. Offers can include an optional observed title for an associated item; missing titles are omitted. Optional tax_included describes the observed price basis: true includes tax, false excludes tax, absence means unknown; it is not a tax calculation. Aggregate offers retain price/high_price bounds and do not establish individual variant prices. Money amount_minor is a decimal string with explicit currency and exponent, not fixed cents."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "example": "",
        "description": "next_cursor from the previous page of the same storefront. Partial refreshes preserve older products until a complete same-scope run establishes absence."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "100",
        "description": "Product-key window size, 1–200 (default 100). Inactive products are omitted; empty pages can have next_cursor. Continue until next_cursor is null to export normalized products. Legacy /shop/products remains unchanged."
      }
    ]
  },
  {
    "id": "shop_catalog_document",
    "path": "/shop/catalog/document",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "shop_products",
      "feature": "shop_catalog",
      "credits": 2
    },
    "npmOperation": "shopCatalogDocument",
    "mcpTool": null,
    "webOperation": null,
    "minTier": "enterprise",
    "params": [
      {
        "name": "platform",
        "in": "query",
        "required": true,
        "example": "wix",
        "description": "Exact platform from the verified catalog response."
      },
      {
        "name": "domain",
        "in": "query",
        "required": true,
        "example": "example.com",
        "description": "Exact reg_domain of the verified storefront."
      },
      {
        "name": "shop_key",
        "in": "query",
        "required": true,
        "example": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "description": "Exact storefront/scope key; a domain alone is not a shop identity."
      },
      {
        "name": "product_key",
        "in": "query",
        "required": true,
        "example": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "description": "Exact product_key of a document_v1 catalog item."
      },
      {
        "name": "run_id",
        "in": "query",
        "required": true,
        "example": "42",
        "description": "Exact positive run ID as decimal text. Superseded references return 409; restart from the current catalog."
      },
      {
        "name": "document_key",
        "in": "query",
        "required": true,
        "example": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        "description": "Exact item.document.document key. Only the current completed product reference is readable; pending upload parts are not exposed."
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "example": "",
        "description": "Signed next_cursor from the previous page; reuse all identity parameters. Null next_cursor and complete=true mean the full manifest commitment has been verified. Key rotation invalidates old cursors; restart without a cursor."
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "example": "4",
        "description": "Part count 1–8, default 4. Each part is at most 256 KiB before hex encoding. Concatenate decoded data_hex bytes in ordinal order before UTF-8/JSON decoding; parts can split characters or JSON tokens. Manifest byte/part counts, run IDs, offer counts and ordinals are decimal strings. Money in the reconstructed document is already decimal minor strings with explicit currency/exponent. No automatic whole-document buffering is performed by the npm helper."
      }
    ]
  },
  {
    "id": "tech_catalog",
    "path": "/techlist",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "catalog_read",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": []
  },
  {
    "id": "tech_catalog_grouped",
    "path": "/techlist/grouped",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "catalog_read",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": []
  },
  {
    "id": "tech_metadata",
    "path": "/techmeta",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "catalog_read",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": [
      {
        "name": "name",
        "in": "query",
        "required": false,
        "example": "React",
        "description": "One technology by name (any case) or route slug; omit for the whole catalog"
      }
    ]
  },
  {
    "id": "tld_catalog",
    "path": "/tlds",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "catalog_read",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": []
  },
  {
    "id": "filter_manifest",
    "path": "/filters",
    "scope": "versioned",
    "method": "GET",
    "auth": "api_key",
    "meter": {
      "action": "catalog_read",
      "feature": "search",
      "credits": 0
    },
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": "free",
    "params": []
  },
  {
    "id": "preview_config",
    "path": "/preview/config",
    "scope": "versioned",
    "method": "GET",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getPreviewConfig",
    "minTier": null,
    "params": null
  },
  {
    "id": "preview_session",
    "path": "/preview/session",
    "scope": "versioned",
    "method": "POST",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "previewSession",
    "minTier": null,
    "params": null
  },
  {
    "id": "search_preview",
    "path": "/preview/search",
    "scope": "versioned",
    "method": "POST",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "previewSearch",
    "minTier": null,
    "params": null
  },
  {
    "id": "api_capabilities",
    "path": "/capabilities",
    "scope": "versioned",
    "method": "GET",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getApiCapabilities",
    "minTier": null,
    "params": null
  },
  {
    "id": "signup",
    "path": "/auth/signup",
    "scope": "versioned",
    "method": "POST",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "signup",
    "minTier": null,
    "params": null
  },
  {
    "id": "login",
    "path": "/auth/login",
    "scope": "versioned",
    "method": "POST",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "login",
    "minTier": null,
    "params": null
  },
  {
    "id": "logout",
    "path": "/auth/logout",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "logout",
    "minTier": null,
    "params": null
  },
  {
    "id": "password_change",
    "path": "/auth/password/change",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "changePassword",
    "minTier": null,
    "params": null
  },
  {
    "id": "password_reset",
    "path": "/auth/password/reset",
    "scope": "versioned",
    "method": "POST",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "resetPassword",
    "minTier": null,
    "params": null
  },
  {
    "id": "invitation_resolve",
    "path": "/invitations/resolve",
    "scope": "versioned",
    "method": "POST",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "resolveInvitation",
    "minTier": null,
    "params": null
  },
  {
    "id": "invitation_accept",
    "path": "/invitations/accept",
    "scope": "versioned",
    "method": "POST",
    "auth": "public",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "acceptInvitation",
    "minTier": null,
    "params": null
  },
  {
    "id": "me",
    "path": "/me",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getMe",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_detail",
    "path": "/organizations/{organization_id}",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getOrganization",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_update",
    "path": "/organizations/{organization_id}",
    "scope": "versioned",
    "method": "PATCH",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "updateOrganization",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_members",
    "path": "/organizations/{organization_id}/members",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getMembers",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_member_update",
    "path": "/organizations/{organization_id}/members/{account_id}",
    "scope": "versioned",
    "method": "PATCH",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "updateMemberRole",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_member_remove",
    "path": "/organizations/{organization_id}/members/{account_id}",
    "scope": "versioned",
    "method": "DELETE",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "removeMember",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_invitations",
    "path": "/organizations/{organization_id}/invitations",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getInvitations",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_invitation_create",
    "path": "/organizations/{organization_id}/invitations",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "createInvitation",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_invitation_revoke",
    "path": "/organizations/{organization_id}/invitations/{invitation_id}",
    "scope": "versioned",
    "method": "DELETE",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "revokeInvitation",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_ownership_transfer",
    "path": "/organizations/{organization_id}/ownership",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "transferOwnership",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_usage",
    "path": "/organizations/{organization_id}/usage",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getOrganizationUsage",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_keys",
    "path": "/organizations/{organization_id}/keys",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_key_create",
    "path": "/organizations/{organization_id}/keys",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "createOrganizationKey",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_key_revoke",
    "path": "/organizations/{organization_id}/keys/{key_prefix}",
    "scope": "versioned",
    "method": "DELETE",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "revokeOrganizationKey",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_billing",
    "path": "/organizations/{organization_id}/billing",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getBilling",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_billing_checkout",
    "path": "/organizations/{organization_id}/billing/checkout",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "startCheckout",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_billing_topup",
    "path": "/organizations/{organization_id}/billing/topup",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "startTopup",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_billing_checkout_status",
    "path": "/organizations/{organization_id}/billing/checkout/{session_id}",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getCheckoutStatus",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_billing_change",
    "path": "/organizations/{organization_id}/billing/change",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "changeBillingTier",
    "minTier": null,
    "params": null
  },
  {
    "id": "organization_billing_portal",
    "path": "/organizations/{organization_id}/billing/portal",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "openBillingPortal",
    "minTier": null,
    "params": null
  },
  {
    "id": "stripe_webhook",
    "path": "/billing/webhook",
    "scope": "root",
    "method": "POST",
    "auth": "stripe_signature",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": null,
    "params": null
  },
  {
    "id": "account",
    "path": "/account",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "getAccount",
    "minTier": null,
    "params": null
  },
  {
    "id": "account_key_create",
    "path": "/account/keys",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "createKey",
    "minTier": null,
    "params": null
  },
  {
    "id": "account_key_revoke",
    "path": "/account/keys/revoke",
    "scope": "versioned",
    "method": "POST",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": "revokeKey",
    "minTier": null,
    "params": null
  },
  {
    "id": "dashboard_shops",
    "path": "/dashboard/shops",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": null,
    "params": null
  },
  {
    "id": "dashboard_shop_stats",
    "path": "/dashboard/shops/stats",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": null,
    "params": null
  },
  {
    "id": "dashboard_shop_products",
    "path": "/dashboard/shop/products",
    "scope": "versioned",
    "method": "GET",
    "auth": "session",
    "meter": null,
    "npmOperation": null,
    "mcpTool": null,
    "webOperation": null,
    "minTier": null,
    "params": null
  }
];

export const CUSTOMER_API_ROUTES = Object.freeze(Object.fromEntries(
  routeList.map((route) => [route.id, Object.freeze(route)]),
));

// One row per tier, mirroring meter.rs (the gateway validates the source JSON against the
// authoritative Tier methods at registry init). null caps mean uncapped; enterprise's 0 monthly
// credits mean unlimited/custom.
export const CUSTOMER_API_TIER_MATRIX = Object.freeze(
  [
  {
    "tier": "free",
    "label": "Free",
    "features": [
      "search",
      "tech"
    ],
    "regex": false,
    "result_depth": 50,
    "export_rows": 0,
    "rate_per_min": 10,
    "monthly_credits": 200,
    "price_usd_month": 0
  },
  {
    "tier": "solo",
    "label": "Solo",
    "features": [
      "search",
      "tech",
      "export"
    ],
    "regex": true,
    "result_depth": 2500,
    "export_rows": 5000,
    "rate_per_min": 60,
    "monthly_credits": 2500,
    "price_usd_month": 19
  },
  {
    "tier": "pro",
    "label": "Pro",
    "features": [
      "search",
      "tech",
      "export",
      "profile",
      "owner_graph"
    ],
    "regex": true,
    "result_depth": 50000,
    "export_rows": 50000,
    "rate_per_min": 120,
    "monthly_credits": 12000,
    "price_usd_month": 79
  },
  {
    "tier": "scale",
    "label": "Scale",
    "features": [
      "search",
      "tech",
      "export",
      "profile",
      "owner_graph"
    ],
    "regex": true,
    "result_depth": null,
    "export_rows": 500000,
    "rate_per_min": 300,
    "monthly_credits": 35000,
    "price_usd_month": 199
  },
  {
    "tier": "enterprise",
    "label": "Enterprise",
    "features": [
      "search",
      "tech",
      "export",
      "profile",
      "owner_graph",
      "shop_catalog"
    ],
    "regex": true,
    "result_depth": null,
    "export_rows": null,
    "rate_per_min": 1000,
    "monthly_credits": 0,
    "price_usd_month": null,
    "price_from_usd_month": 899
  }
].map((entry) => Object.freeze(entry)),
);

export const TIER_ORDER = Object.freeze(["free","solo","pro","scale","enterprise"]);

// Published pricing constants (credit price, top-up bundle, overage rate for rows beyond a
// plan's result depth). The gateway cross-checks them against meter.rs at registry init.
export const CUSTOMER_API_PRICING = Object.freeze({"credit_usd":0.01,"topup":{"usd":10,"credits":1000},"overage_credits_per_100_rows":1,"regex_search_surcharge_credits":5});

export const CUSTOMER_API_KEY_ROUTE_IDS = Object.freeze(
  routeList.filter((route) => route.auth === "api_key").map((route) => route.id),
);
export const NPM_OPERATION_ROUTE_IDS = Object.freeze(Object.fromEntries(
  routeList.filter((route) => route.npmOperation).map((route) => [route.npmOperation, route.id]),
));
export const MCP_TOOL_ROUTE_IDS = Object.freeze(Object.fromEntries(
  routeList.filter((route) => route.mcpTool).map((route) => [route.mcpTool, route.id]),
));
export const WEB_OPERATION_ROUTE_IDS = Object.freeze(Object.fromEntries(
  routeList.filter((route) => route.webOperation).map((route) => [route.webOperation, route.id]),
));

export function customerApiRoute(id) {
  const route = CUSTOMER_API_ROUTES[id];
  if (!route) throw new Error(`unknown customer API route: ${id}`);
  return route;
}

export function customerApiPath(id, params = {}) {
  const route = customerApiRoute(id);
  const path = route.path.replace(/\{([^}]+)\}/g, (_match, name) => {
    const value = params[name];
    if (value === undefined || value === null || value === "") {
      throw new Error(`missing path parameter ${name} for customer API route ${id}`);
    }
    return encodeURIComponent(String(value));
  });
  if (/\{[^}]+\}/.test(path)) throw new Error(`unresolved path parameter for ${id}`);
  return path;
}
